import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import { AuthContextProvider } from "@/context/AuthContext";
import Navbar from "@/components/shared/Navbar";
import Providers from "@/components/Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="en">
      <body>
        <Providers>
          <AuthContextProvider>
            <SidebarProvider>
              <AppSidebar />
              <main className="w-full">
                <Navbar />
                { children }
              </main>
            </SidebarProvider>
          </AuthContextProvider>
        </Providers>
      </body>
    </html>
  );
}
